### Endpoint de teste
GET http://localhost:3003/ping

### Get all users
GET http://localhost:3003/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0NjJiMjg0LWEyOGQtNGM2MC05ZjYyLTczNDJkZDllZmIyZSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5ODk5NzEsImV4cCI6MTY2MDA3NjM3MX0.7KY_AeTeH3x_cplcwoXxG2Vx7M4zX5t2u-zS49RjfbE

### Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Pâmela",
    "email": "pamelamaiara1998@gmail.com",
    "password": "abc123"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### Delete user
DELETE http://localhost:3003/users/7079b8e4-95cd-48aa-82a9-77454e94b789
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDA1MzkxOSwiZXhwIjoxNjYwMTQwMzE5fQ.8vZjLku4skXWy76OdA7ienPdNe3YWos1zsrFrq-wvrk
