### Endpoint de test
GET http://localhost:3003/ping

### Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "astrodev",
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Create pizza
POST http://localhost:3003/pizza
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTM2NjQ5NiwiZXhwIjoxNjYxNDUyODk2fQ.AGS4QF7RrKZO4NDlIi72PX25tUkiep-U_HRztnzluik

Content-Type: application/json

### 5) Delete pizza
DELETE http://localhost:3003/pizzas/301
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTM2NjQ5NiwiZXhwIjoxNjYxNDUyODk2fQ.AGS4QF7RrKZO4NDlIi72PX25tUkiep-U_HRztnzluik

### 6) Get pizzas
GET http://localhost:3003/pizzas
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkxMGI4MTI2LTQyZTAtNGU3MS1hN2I5LWM0NDYzMWMwNmQwNyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjEzNjU0NzIsImV4cCI6MTY2MTQ1MTg3Mn0.97CJxjiaXDz8EIvpS9D1p1LR-fxw14Yxr9PRNSkterY
